name: Docker Image CI

on:
  push:
    branches:
      - "*"
      - "*/*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & Test
        run: docker build . --tag image

      - name: Publish
        if: github.ref_type == 'tag'
        run: docker run image --api-key $NUGET_API_KEY
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
